IF OBJECT_ID('dbo.Client', 'V') IS NOT NULL
    DROP VIEW dbo.Client;
GO

CREATE VIEW dbo.Client
AS

SELECT 
	 OdsPostingGroupAuditId
	,OdsCustomerId
	,OdsCreateDate
	,OdsSnapshotDate
	,OdsRowIsCurrent
	,OdsHashbytesValue
	,DmlOperation
	,ClientCode
	,Name
	,Jurisdiction
	,ControlNum
	,PolicyTimeLimit
	,PolicyLimitWarningPct
	,PolicyLimit
	,PolicyDeductible
	,PolicyCoPayPct
	,PolicyCoPayAmount
	,BEDiagnosis
	,InvoiceBRCycle
	,Status
	,InvoiceGroupBy
	,BEDOI
	,DrugMarkUpBrand
	,SupplyLimit
	,InvoicePPOCycle
	,InvoicePPOTax
	,DrugMarkUpGen
	,DrugDispGen
	,DrugDispBrand
	,BEAdjuster
	,InvoiceTax
	,CompanySeq
	,BEMedAlert
	,UCRPercentile
	,ClientComment
	,RemitAttention
	,RemitAddress1
	,RemitAddress2
	,RemitCityStateZip
	,RemitPhone
	,ExternalID
	,BEOther
	,MedAlertDays
	,MedAlertVisits
	,MedAlertMaxCharge
	,MedAlertWarnVisits
	,ProviderSubSet
	,AllowReReview
	,AcctRep
	,ClientType
	,UCRMarkUp
	,InvoiceCombined
	,BESubmitDt
	,BERcvdCarrierDate
	,BERcvdBillReviewDate
	,BEDueDate
	,ProductCode
	,BEProvInvoice
	,ClaimSysSubSet
	,DefaultBRtoUCR
	,BasePPOFeesOffFS
	,BEClientTOBTableCode
	,BEForcePay
	,BEPayAuthorization
	,BECarrierSeqFlag
	,BEProvTypeTableCode
	,BEProvSpcl1TableCode
	,BEProvLicense
	,BEPayAuthTableCode
	,PendReasonTableCode
	,VocRehab
	,EDIAckRequired
	,StateRptInd
	,BEPatientAcctNum
	,AutoDup
	,UseAllowOnDup
	,URImportUsed
	,URProgStartDate
	,URImportCtrlNum
	,URImportCtrlGroup
	,UCRSource
	,UCRMarkup2
	,NGDTableCode
	,BESubProductTableCode
	,CountryTableCode
	,BERefPhys
	,BEPmtWarnDays
	,GeoState
	,BEDisableDOICheck
	,DelayDays
	,BEValidateTotal
	,BEFastMatch
	,BEPriorBillDefault
	,BEClientDueDays
	,BEAutoCalcDueDate
	,UCRSource2
	,UCRPercentile2
	,BEProvSpcl2TableCode
	,FeeRateCntrlEx
	,FeeRateCntrlIn
	,BECollisionProvBills
	,BECollisionBills
	,SupplyMarkup
	,BECollisionProviders
	,DefaultCoPayDeduct
	,AutoBundling
	,BEValidateBillClaimICD9
	,EnableGenericReprice
	,BESubProdFeeInfo
	,DenyNonInjDrugs
	,BECollisionDosLines
	,PPOProfileSiteCode
	,PPOProfileID
	,BEShowDEAWarning
	,BEHideAdjusterColumn
	,BEHideCoPayColumn
	,BEHideDeductColumn
	,BEPaidDate
	,BEProcCrossWalk
	,CreateUserID
	,CreateDate
	,ModUserID
	,ModDate
	,BEConsultDate
	,BEShowPharmacyColumns
	,BEAdjVerifDates
	,FutureDOSMonthLimit
	,BEStopAtLineUnits
	,BENYNF10Fields
	,EnableDRGGrouper
	,ApplyCptAmaUcrRules
	,BEProvSigOnFile
	,BETimeEntry
	,SalesTaxExempt
	,InvoiceRetailProfile
	,InvoiceWholesaleProfile
	,BEDefaultTaxZip
	,ReceiptHandlingCode
	,PaymentHandlingCode
	,DefaultRetailSalesTaxZip
	,DefaultWholesaleSalesTaxZip
	,TxNonSubscrib
	,RootClaimLength
	,BEDAWTableCode
	,EORProfileSeq
	,BEOtherBillingProvider
	,BEDocCtrlID
	,ReportingETL
	,ClaimVerification
	,ProvVerification
	,BEPermitAllowOver
	,BEStopAtLineDxRef
	,BEQuickInfoCode
	,ExcludedSmartClientSelect
	,CollisionsSearchBy
	,AutoDupIncludeProv
	,URProfileID
	,ExcludeURDM
	,BECollisionURCases
	,MUEEdits
	,CPTRarity
	,ICDRarity
	,ICDToCPTRarity
	,BEDisablePPOSearch
	,BEShowLineExternalIDColumn
	,BEShowLinePriorAuthColumn
	,SmartGuidelinesFlag
	,BEProvBillingLicense
	,BEProvFacilityLicense
	,VendorProviderSubSet
	,DefaultJurisClientCode
	,ClientGroupId
	,DrugDispFeeApplyTo
FROM src.Client
WHERE   OdsRowIsCurrent = 1
	AND DmlOperation <> 'D';
GO


