IF OBJECT_ID('dbo.Bill', 'V') IS NOT NULL
    DROP VIEW dbo.Bill;
GO

CREATE VIEW dbo.Bill
AS

SELECT 
	 OdsPostingGroupAuditId
	,OdsCustomerId
	,OdsCreateDate
	,OdsSnapshotDate
	,OdsRowIsCurrent
	,OdsHashbytesValue
	,DmlOperation
	,ClientCode
	,BillSeq
	,ClaimSeq
	,ClaimSysSubSet
	,ProviderSeq
	,ProviderSubSet
	,PostDate
	,DOSFirst
	,Invoiced
	,InvoicedPPO
	,CreateUserID
	,CarrierSeqNew
	,DocCtrlType
	,DOSLast
	,PPONetworkID
	,POS
	,ProvType
	,ProvSpecialty1
	,ProvZip
	,ProvState
	,SubmitDate
	,ProvInvoice
	,Region
	,HospitalSeq
	,ModUserID
	,Status
	,StatusPrior
	,BillableLines
	,TotalCharge
	,BRReduction
	,BRFee
	,TotalAllow
	,TotalFee
	,DupClientCode
	,DupBillSeq
	,FupStartDate
	,FupEndDate
	,SendBackMsg1SiteCode
	,SendBackMsg1
	,SendBackMsg2SiteCode
	,SendBackMsg2
	,PPOReduction
	,PPOPrc
	,PPOContractID
	,PPOStatus
	,PPOFee
	,NGDReduction
	,NGDFee
	,URFee
	,OtherData
	,ExternalStatus
	,URFlag
	,Visits
	,TOS
	,TOB
	,SubProductCode
	,ForcePay
	,PmtAuth
	,FlowStatus
	,ConsultDate
	,RcvdDate
	,AdmissionType
	,PaidDate
	,AdmitDate
	,DischargeDate
	,TxBillType
	,RcvdBrDate
	,DueDate
	,Adjuster
	,DOI
	,RetCtrlFlg
	,RetCtrlNum
	,SiteCode
	,SourceID
	,CaseType
	,SubProductID
	,SubProductPrice
	,URReduction
	,ProvLicenseNum
	,ProvMedicareNum
	,ProvSpecialty2
	,PmtExportDate
	,PmtAcceptDate
	,ClientTOB
	,BRFeeNet
	,PPOFeeNet
	,NGDFeeNet
	,URFeeNet
	,SubProductPriceNet
	,BillSeqNewRev
	,BillSeqOrgRev
	,VocPlanSeq
	,ReviewDate
	,AuditDate
	,ReevalAllow
	,CheckNum
	,NegoType
	,DischargeHour
	,UB92TOB
	,MCO
	,DRG
	,PatientAccount
	,ExaminerRevFlag
	,RefProvName
	,PaidAmount
	,AdmissionSource
	,AdmitHour
	,PatientStatus
	,DRGValue
	,CompanySeq
	,TotalCoPay
	,UB92ProcMethod
	,TotalDeductible
	,PolicyCoPayAmount
	,PolicyCoPayPct
	,DocCtrlID
	,ResourceUtilGroup
	,PolicyDeductible
	,PolicyLimit
	,PolicyTimeLimit
	,PolicyWarningPct
	,AppBenefits
	,AppAssignee
	,CreateDate
	,ModDate
	,IncrementValue
	,AdjVerifRequestDate
	,AdjVerifRcvdDate
	,RenderingProvLastName
	,RenderingProvFirstName
	,RenderingProvMiddleName
	,RenderingProvSuffix
	,RereviewCount
	,DRGBilled
	,DRGCalculated
	,ProvRxLicenseNum
	,ProvSigOnFile
	,RefProvFirstName
	,RefProvMiddleName
	,RefProvSuffix
	,RefProvDEANum
	,SendbackMsg1Subset
	,SendbackMsg2Subset
	,PPONetworkJurisdictionInd
	,ManualReductionMode
	,WholesaleSalesTaxZip
	,RetailSalesTaxZip
	,PPONetworkJurisdictionInsurerSeq
	,InvoicedWholesale
	,InvoicedPPOWholesale
	,AdmittingDxRef
	,AdmittingDxCode
	,ProvFacilityNPI
	,ProvBillingNPI
	,ProvRenderingNPI
	,ProvOperatingNPI
	,ProvReferringNPI
	,ProvOther1NPI
	,ProvOther2NPI
	,ProvOperatingLicenseNum
	,EHubID
	,OtherBillingProviderSubset
	,OtherBillingProviderSeq
	,ResubmissionReasonCode
	,ContractType
	,ContractAmount
	,PriorAuthReferralNum1
	,PriorAuthReferralNum2
	,DRGCompositeFactor
	,DRGDischargeFraction
	,DRGInpatientMultiplier
	,DRGWeight
	,EFTPmtMethodCode
	,EFTPmtFormatCode
	,EFTSenderDFIID
	,EFTSenderAcctNum
	,EFTOrigCoSupplCode
	,EFTReceiverDFIID
	,EFTReceiverAcctQual
	,EFTReceiverAcctNum
	,PolicyLimitResult
	,HistoryBatchNumber
	,ProvBillingTaxonomy
	,ProvFacilityTaxonomy
	,ProvRenderingTaxonomy
	,PPOStackList
	,ICDVersion
	,ODGFlag
	,ProvBillLicenseNum
	,ProvFacilityLicenseNum
	,ProvVendorExternalID
	,BRActualClientCode
	,BROverrideClientCode
	,BillReevalReasonCode
	,PaymentClearedDate
	,EstimatedBRClientCode
	,EstimatedBRJuris
	,OverrideFeeControlRetail
	,OverrideFeeControlWholesale
	,StatementFromDate
	,StatementThroughDate
FROM src.Bill
WHERE   OdsRowIsCurrent = 1
	AND DmlOperation <> 'D';
GO


