IF OBJECT_ID('src.prf_Profile', 'U') IS NULL
    BEGIN
    CREATE TABLE src.prf_Profile
        (
            OdsPostingGroupAuditId INT NOT NULL ,
            OdsCustomerId INT NOT NULL ,
            OdsCreateDate DATETIME2(7) NOT NULL ,
            OdsSnapshotDate DATETIME2(7) NOT NULL ,
            OdsRowIsCurrent BIT NOT NULL ,
            OdsHashbytesValue VARBINARY(8000) NULL ,
            DmlOperation CHAR(1) NOT NULL ,
			ProfileId INT NOT NULL,
			OfficeId INT NULL,
			CoverageId VARCHAR(2) NULL,
			StateId VARCHAR(2) NULL,
			AnHeader VARCHAR(MAX) NULL,
			AnFooter VARCHAR(MAX) NULL,
			ExHeader VARCHAR(MAX) NULL,
			ExFooter VARCHAR(MAX) NULL,
			AnalystEdits BIGINT NULL,
			DxEdits INT NULL,
			DxNonTraumaDays INT NULL,
			DxNonSpecDays INT NULL,
			PrintCopies INT NULL,
			NewPvdState VARCHAR(2) NULL,
			bDuration SMALLINT NULL,
			bLimits SMALLINT NULL,
			iDurPct SMALLINT NULL,
			iLimitPct SMALLINT NULL,
			PolicyLimit MONEY NULL,
			CoPayPercent INT NULL,
			CoPayMax MONEY NULL,
			Deductible MONEY NULL,
			PolicyWarn SMALLINT NULL,
			PolicyWarnPerc INT NULL,
			FeeSchedules INT NULL,
			DefaultProfile SMALLINT NULL,
			FeeAncillaryPct SMALLINT NULL,
			iGapdol SMALLINT NULL,
			iGapTreatmnt SMALLINT NULL,
			bGapTreatmnt SMALLINT NULL,
			bGapdol SMALLINT NULL,
			bPrintAdjustor SMALLINT NULL,
			sPrinterName VARCHAR(50) NULL,
			ErEdits INT NULL,
			ErAllowedDays INT NULL,
			UcrFsRules INT NULL,
			LogoIdNo INT NULL,
			LogoJustify SMALLINT NULL,
			BillLine VARCHAR(50) NULL,
			Version SMALLINT NULL,
			ClaimDeductible SMALLINT NULL,
			IncludeCommitted SMALLINT NULL,
			FLMedicarePercent SMALLINT NULL,
			UseLevelOfServiceUrl SMALLINT NULL,
			LevelOfServiceURL VARCHAR(250) NULL,
			CCIPrimary SMALLINT NULL,
			CCISecondary SMALLINT NULL,
			CCIMutuallyExclusive SMALLINT NULL,
			CCIComprehensiveComponent SMALLINT NULL,
			PayDRGAllowance SMALLINT NULL,
			FLHospEmPriceOn SMALLINT NULL,
			EnableBillRelease SMALLINT NULL,
			DisableSubmitBill SMALLINT NULL,
			MaxPaymentsPerBill SMALLINT NULL,
			NoOfPmtPerBill INT NULL,
			DefaultDueDate SMALLINT NULL,
			CheckForNJCarePaths SMALLINT NULL,
			NJCarePathPercentFS SMALLINT NULL,
			ApplyEndnoteForNJCarePaths SMALLINT NULL,
			FLMedicarePercent2008 SMALLINT NULL,
			RequireEndnoteDuringOverride SMALLINT NULL,
			StorePerUnitFSandUCR SMALLINT NULL,
			UseProviderNetworkEnrollment SMALLINT NULL,
			UseASCRule SMALLINT NULL,
			AsstCoSurgeonEligible SMALLINT NULL,
			LastChangedOn datetime NULL,
			IsNJPhysMedCapAfterCTG SMALLINT NULL,
			IsEligibleAmtFeeBased SMALLINT NULL,
			HideClaimTreeTotalsGrid SMALLINT NULL,
			SortBillsBy SMALLINT NULL,
			SortBillsByOrder SMALLINT NULL,
			ApplyNJEmergencyRoomBenchmarkFee SMALLINT NULL,
			AllowIcd10ForNJCarePaths SMALLINT NULL,
			EnableOverrideDeductible BIT NULL,
			AnalyzeDiagnosisPointers BIT NULL,
			MedicareFeePercent SMALLINT NULL,
			EnableSupplementalNdcData BIT NULL,
			ApplyOriginalNdcAwp BIT NULL,
			NdcAwpNotAvailable TINYINT NULL,
			PayEapgAllowance SMALLINT NULL,
			MedicareInpatientApcEnabled BIT NULL,
			MedicareOutpatientAscEnabled BIT NULL,
			MedicareAscEnabled BIT NULL,
			UseMedicareInpatientApcFee BIT NULL,
			MedicareInpatientDrgEnabled BIT NULL,
			MedicareInpatientDrgPricingType SMALLINT NULL,
			MedicarePhysicianEnabled BIT NULL,
			MedicareAmbulanceEnabled BIT NULL,
			MedicareDmeposEnabled BIT NULL,
			MedicareAspDrugAndClinicalEnabled BIT NULL,
			MedicareInpatientPricingType SMALLINT NULL,
			MedicareOutpatientPricingRulesEnabled BIT NULL,
			MedicareAscPricingRulesEnabled BIT NULL,
			NjUseAdmitTypeEnabled BIT NULL,
			MedicareClinicalLabEnabled BIT NULL,
			MedicareInpatientEnabled BIT NULL,
			MedicareOutpatientApcEnabled BIT NULL,
			MedicareAspDrugEnabled BIT NULL,
			ShowAllocationsOnEob BIT NULL,
			EmergencyCarePricingRuleId TINYINT NULL,
			OutOfStatePricingEffectiveDateId TINYINT NULL,
			PreAllocation BIT NULL,
			AssistantCoSurgeonModifiers SMALLINT NULL,
			AssistantSurgeryModifierNotMedicallyNecessary SMALLINT NULL,
			AssistantSurgeryModifierRequireAdditionalDocument SMALLINT NULL,
			CoSurgeryModifierNotMedicallyNecessary SMALLINT NULL,
			CoSurgeryModifierRequireAdditionalDocument SMALLINT NULL,
			DxNoDiagnosisDays INT NULL,
			ModifierExempted BIT NULL
            )
        ON  DP_Ods_PartitionScheme(OdsCustomerId)
            WITH (
                 DATA_COMPRESSION = PAGE);

        ALTER TABLE src.prf_Profile ADD 
        CONSTRAINT PK_prf_Profile PRIMARY KEY CLUSTERED (OdsPostingGroupAuditId, OdsCustomerId, ProfileId) WITH (DATA_COMPRESSION = PAGE) ON DP_Ods_PartitionScheme(OdsCustomerId);
		
		ALTER INDEX PK_prf_Profile ON src.prf_Profile REBUILD WITH(STATISTICS_INCREMENTAL = ON);

    END;
GO
