IF OBJECT_ID('stg.BILLS_DRG', 'U') IS NOT NULL 
	DROP TABLE stg.BILLS_DRG  
BEGIN
	CREATE TABLE stg.BILLS_DRG
		(
		  BillIdNo INT NULL,
		  PricerPassThru MONEY NULL,
		  PricerCapital_Outlier_Amt MONEY NULL,
		  PricerCapital_OldHarm_Amt MONEY NULL,
		  PricerCapital_IME_Amt MONEY NULL,
		  PricerCapital_HSP_Amt MONEY NULL,
		  PricerCapital_FSP_Amt MONEY NULL,
		  PricerCapital_Exceptions_Amt MONEY NULL,
		  PricerCapital_DSH_Amt MONEY NULL,
		  PricerCapitalPayment MONEY NULL,
		  PricerDSH MONEY NULL,
		  PricerIME MONEY NULL,
		  PricerCostOutlier MONEY NULL,
		  PricerHSP MONEY NULL,
		  PricerFSP MONEY NULL,
		  PricerTotalPayment MONEY NULL,
		  PricerReturnMsg VARCHAR (255) NULL,
		  ReturnDRG VARCHAR (3) NULL,
		  ReturnDRGDesc VARCHAR (125) NULL,
		  ReturnMDC VARCHAR (3) NULL,
		  ReturnMDCDesc VARCHAR (100) NULL,
		  ReturnDRGWt REAL NULL,
		  ReturnDRGALOS REAL NULL,
		  ReturnADX VARCHAR (8) NULL,
		  ReturnSDX VARCHAR (8) NULL,
		  ReturnMPR VARCHAR (8) NULL,
		  ReturnPR2 VARCHAR (8) NULL,
		  ReturnPR3 VARCHAR (8) NULL,
		  ReturnNOR VARCHAR (8) NULL,
		  ReturnNO2 VARCHAR (8) NULL,
		  ReturnCOM VARCHAR (255) NULL,
		  ReturnCMI SMALLINT NULL,
		  ReturnDCC VARCHAR (8) NULL,
		  ReturnDX1 VARCHAR (8) NULL,
		  ReturnDX2 VARCHAR (8) NULL,
		  ReturnDX3 VARCHAR (8) NULL,
		  ReturnMCI SMALLINT NULL,
		  ReturnOR1 VARCHAR (8) NULL,
		  ReturnOR2 VARCHAR (8) NULL,
		  ReturnOR3 VARCHAR (8) NULL,
		  ReturnTRI SMALLINT NULL,
		  SOJ VARCHAR (2) NULL,
		  OPCERT VARCHAR (7) NULL,
		  BlendCaseInclMalp REAL NULL,
		  CapitalCost REAL NULL,
		  HospBadDebt REAL NULL,
		  ExcessPhysMalp REAL NULL,
		  SparcsPerCase REAL NULL,
		  AltLevelOfCare REAL NULL,
		  DRGWgt REAL NULL,
		  TransferCapital REAL NULL,
		  NYDrgType SMALLINT NULL,
		  LOS SMALLINT NULL,
		  TrimPoint SMALLINT NULL,
		  GroupBlendPercentage REAL NULL,
		  AdjustmentFactor REAL NULL,
		  HospLongStayGroupPrice REAL NULL,
		  TotalDRGCharge MONEY NULL,
		  BlendCaseAdj REAL NULL,
		  CapitalCostAdj REAL NULL,
		  NonMedicareCaseMix REAL NULL,
		  HighCostChargeConverter REAL NULL,
		  DischargeCasePaymentRate MONEY NULL,
		  DirectMedicalEducation MONEY NULL,
		  CasePaymentCapitalPerDiem MONEY NULL,
		  HighCostOutlierThreshold MONEY NULL,
		  ISAF REAL NULL,
		  ReturnSOI SMALLINT NULL,
		  CapitalCostPerDischarge MONEY NULL,
		  ReturnSOIDesc VARCHAR (20) NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

