IF OBJECT_ID('stg.CMT_HDR', 'U') IS NOT NULL
DROP TABLE stg.CMT_HDR
BEGIN
	CREATE TABLE stg.CMT_HDR (
		CMT_HDR_IDNo INT NULL
		,CmtIDNo INT NULL
		,PvdIDNo INT NULL
		,LastChangedOn DATETIME NULL
		,DmlOperation CHAR(1) NOT NULL
		)
END
GO
