IF OBJECT_ID('stg.CMT_ICD9', 'U') IS NOT NULL
DROP TABLE stg.CMT_ICD9
BEGIN
	CREATE TABLE stg.CMT_ICD9 (
		BillIDNo INT NULL
		,SeqNo SMALLINT NULL
		,ICD9 VARCHAR(7) NULL
		,IcdVersion TINYINT NULL
		,DmlOperation CHAR(1) NOT NULL
		)
END
GO
