IF OBJECT_ID('stg.CMT_DX', 'U') IS NOT NULL
DROP TABLE stg.CMT_DX
BEGIN
	CREATE TABLE stg.CMT_DX (
		BillIDNo INT NULL
		,DX VARCHAR(8) NULL
		,SeqNum SMALLINT NULL
		,POA VARCHAR(1) NULL
		,IcdVersion TINYINT NULL
		,DmlOperation CHAR(1) NOT NULL
		)
END 
GO   
