IF OBJECT_ID('stg.BILL_HDR', 'U') IS NOT NULL 
	DROP TABLE stg.BILL_HDR  
BEGIN
	CREATE TABLE stg.BILL_HDR
		(
		  BillIDNo INT NULL,
		  CMT_HDR_IDNo INT NULL,
		  DateSaved DATETIME NULL,
		  DateRcv DATETIME NULL,
		  InvoiceNumber VARCHAR (40) NULL,
		  InvoiceDate DATETIME NULL,
		  FileNumber VARCHAR (50) NULL,
		  Note VARCHAR (20) NULL,
		  NoLines SMALLINT NULL,
		  AmtCharged MONEY NULL,
		  AmtAllowed MONEY NULL,
		  ReasonVersion SMALLINT NULL,
		  Region VARCHAR (50) NULL,
		  PvdUpdateCounter SMALLINT NULL,
		  FeatureID INT NULL,
		  ClaimDateLoss DATETIME NULL,
		  CV_Type VARCHAR (2) NULL,
		  Flags INT NULL,
		  WhoCreate VARCHAR (15) NULL,
		  WhoLast VARCHAR (15) NULL,
		  AcceptAssignment SMALLINT NULL,
		  EmergencyService SMALLINT NULL,
		  CmtPaidDeductible MONEY NULL,
		  InsPaidLimit MONEY NULL,
		  StatusFlag VARCHAR (2) NULL,
		  OfficeId INT NULL,
		  CmtPaidCoPay MONEY NULL,
		  AmbulanceMethod SMALLINT NULL,
		  StatusDate DATETIME NULL,
		  Category INT NULL,
		  CatDesc VARCHAR (1000) NULL,
		  AssignedUser VARCHAR (15) NULL,
		  CreateDate DATETIME NULL,
		  PvdZOS VARCHAR (12) NULL,
		  PPONumberSent SMALLINT NULL,
		  AdmissionDate DATETIME NULL,
		  DischargeDate DATETIME NULL,
		  DischargeStatus SMALLINT NULL,
		  TypeOfBill VARCHAR (4) NULL,
		  SentryMessage VARCHAR (1000) NULL,
		  AmbulanceZipOfPickup VARCHAR (12) NULL,
		  AmbulanceNumberOfPatients SMALLINT NULL,
		  WhoCreateID INT NULL,
		  WhoLastId INT NULL,
		  NYRequestDate DATETIME NULL,
		  NYReceivedDate DATETIME NULL,
		  ImgDocId VARCHAR (50) NULL,
		  PaymentDecision SMALLINT NULL,
		  PvdCMSId VARCHAR (6) NULL,
		  PvdNPINo VARCHAR (15) NULL,
		  DischargeHour VARCHAR (2) NULL,
		  PreCertChanged SMALLINT NULL,
		  DueDate DATETIME NULL,
		  AttorneyIDNo INT NULL,
		  AssignedGroup INT NULL,
		  LastChangedOn DATETIME NULL,
		  PrePPOAllowed MONEY NULL,
		  PPSCode SMALLINT NULL,
		  SOI SMALLINT NULL,
		  StatementStartDate DATETIME NULL,
		  StatementEndDate DATETIME NULL,
		  DeductibleOverride BIT NULL,
		  AdmissionType TINYINT NULL,
		  CoverageType VARCHAR (2) NULL,
		  PricingProfileId INT NULL,
		  DesignatedPricingState VARCHAR (2) NULL,
		  DateAnalyzed DATETIME NULL,
		  SentToPpoSysId INT NULL,
		  PricingState VARCHAR (2) NULL,
		  BillVpnEligible BIT NULL,
		  ApportionmentPercentage DECIMAL (5,2) NULL,
		  BillSourceId TINYINT NULL,
		  OutOfStateProviderNumber INT NULL,
		  FloridaDeductibleRuleEligible BIT NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

