IF OBJECT_ID('stg.SENTRY_RULE_ACTION_HEADER', 'U') IS NOT NULL 
	DROP TABLE stg.SENTRY_RULE_ACTION_HEADER  
BEGIN
	CREATE TABLE stg.SENTRY_RULE_ACTION_HEADER
		(
		  RuleID INT NULL,
		  EndnoteShort VARCHAR (50) NULL,
		  EndnoteLong VARCHAR (MAX) NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

