IF OBJECT_ID('stg.SENTRY_RULE_ACTION_DETAIL', 'U') IS NOT NULL 
	DROP TABLE stg.SENTRY_RULE_ACTION_DETAIL  
BEGIN
	CREATE TABLE stg.SENTRY_RULE_ACTION_DETAIL
		(
		  RuleID INT NULL,
		  LineNumber INT NULL,
		  ActionID INT NULL,
		  ActionValue VARCHAR (1000) NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

