IF OBJECT_ID('stg.Bills', 'U') IS NOT NULL 
	DROP TABLE stg.Bills  
BEGIN
	CREATE TABLE stg.Bills
		(
		  BillIDNo INT NULL,
		  LINE_NO SMALLINT NULL,
		  LINE_NO_DISP SMALLINT NULL,
		  OVER_RIDE SMALLINT NULL,
		  DT_SVC DATETIME NULL,
		  PRC_CD VARCHAR (7) NULL,
		  UNITS REAL NULL,
		  TS_CD VARCHAR (14) NULL,
		  CHARGED MONEY NULL,
		  ALLOWED MONEY NULL,
		  ANALYZED MONEY NULL,
		  REASON1 INT NULL,
		  REASON2 INT NULL,
		  REASON3 INT NULL,
		  REASON4 INT NULL,
		  REASON5 INT NULL,
		  REASON6 INT NULL,
		  REASON7 INT NULL,
		  REASON8 INT NULL,
		  REF_LINE_NO SMALLINT NULL,
		  SUBNET VARCHAR (9) NULL,
		  OverrideReason SMALLINT NULL,
		  FEE_SCHEDULE MONEY NULL,
		  POS_RevCode VARCHAR (4) NULL,
		  CTGPenalty MONEY NULL,
		  PrePPOAllowed MONEY NULL,
		  PPODate DATETIME NULL,
		  PPOCTGPenalty MONEY NULL,
		  UCRPerUnit MONEY NULL,
		  FSPerUnit MONEY NULL,
		  HCRA_Surcharge MONEY NULL,
		  EligibleAmt MONEY NULL,
		  DPAllowed MONEY NULL,
		  EndDateOfService DATETIME NULL,
		  AnalyzedCtgPenalty DECIMAL (19,4) NULL,
		  AnalyzedCtgPpoPenalty DECIMAL (19,4) NULL,
		  RepackagedNdc VARCHAR (13) NULL,
		  OriginalNdc VARCHAR (13) NULL,
		  UnitOfMeasureId TINYINT NULL,
		  PackageTypeOriginalNdc VARCHAR (2) NULL,
		  ServiceCode VARCHAR (25) NULL,
		  PreApportionedAmount DECIMAL (19,4) NULL,
		  DeductibleApplied DECIMAL (19,4) NULL,
		  BillReviewResults DECIMAL (19,4) NULL,
		  PreOverriddenDeductible DECIMAL (19,4) NULL,
		  RemainingBalance DECIMAL (19,4) NULL,
		  CtgCoPayPenalty DECIMAL(19,4) NULL,
		  PpoCtgCoPayPenaltyPercentage DECIMAL(19,4) NULL,
		  AnalyzedCtgCoPayPenalty DECIMAL(19,4) NULL,
		  AnalyzedPpoCtgCoPayPenaltyPercentage DECIMAL(19,4) NULL,
		  CtgVunPenalty DECIMAL(19,4) NULL,
		  PpoCtgVunPenaltyPercentage DECIMAL(19,4) NULL,
		  AnalyzedCtgVunPenalty DECIMAL(19,4) NULL,
		  AnalyzedPpoCtgVunPenaltyPercentage DECIMAL(19,4) NULL,
		  RenderingNpi VARCHAR (15) NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

