IF OBJECT_ID('stg.SENTRY_PROFILE_RULE', 'U') IS NOT NULL 
	DROP TABLE stg.SENTRY_PROFILE_RULE  
BEGIN
	CREATE TABLE stg.SENTRY_PROFILE_RULE
		(
		  ProfileID INT NULL,
		  RuleID INT NULL,
		  Priority INT NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

