IF OBJECT_ID('src.EDIControl', 'U') IS NULL 
	BEGIN
		CREATE TABLE src.EDIControl
			(
			  OdsPostingGroupAuditId INT NOT NULL ,  
			  OdsCustomerId INT NOT NULL , 
			  OdsCreateDate DATETIME2(7) NOT NULL ,
			  OdsSnapshotDate DATETIME2(7) NOT NULL , 
			  OdsRowIsCurrent BIT NOT NULL ,
			  OdsHashbytesValue VARBINARY(8000) NULL ,
			  DmlOperation CHAR(1) NOT NULL ,  
			  EDIControlSeq INT NOT NULL ,
			  EDIMapToolSiteCode CHAR (3) NULL ,
			  EDIPortType CHAR (1) NULL ,
			  EDIMapToolID INT NULL ,
			  Name VARCHAR (50) NULL ,
			  LastTapeDate DATETIME NULL ,
			  LastStartDate DATETIME NULL ,
			  LastEndDate DATETIME NULL ,
			  DayCounter SMALLINT NULL ,
			  TotalCounter INT NULL ,
			  VendorNum VARCHAR (20) NULL ,
			  VendorContact VARCHAR (50) NULL ,
			  VendorPhone VARCHAR (10) NULL ,
			  AccountNum VARCHAR (20) NULL ,
			  OfficeNum VARCHAR (20) NULL ,
			  EDISenderQualifier CHAR (2) NULL ,
			  EDISenderIdentifier VARCHAR (15) NULL ,
			  EDIReceiverQualifier CHAR (2) NULL ,
			  EDIReceiverIdentifier VARCHAR (15) NULL ,
			  EDIAcknowledgement CHAR (1) NULL ,
			  EDITestIndicator CHAR (1) NULL ,
			  ExportCredits CHAR (1) NULL ,
			  ExportNegatives CHAR (1) NULL ,
			  CreateEORs CHAR (1) NULL ,
			  SpecialProcessFlag VARCHAR (120) NULL ,
			  ARCompany VARCHAR (20) NULL ,
			  ARContact VARCHAR (30) NULL ,
			  ARAddr1 VARCHAR (30) NULL ,
			  ARAddr2 VARCHAR (30) NULL ,
			  ARCity VARCHAR (30) NULL ,
			  ARState CHAR (2) NULL ,
			  ARZip VARCHAR (9) NULL ,
			  ARPhone VARCHAR (10) NULL ,
			  EDISenderZIP VARCHAR (9) NULL ,
			  EDIReceiverZIP VARCHAR (9) NULL ,
			  CreateDate DATETIME NULL ,
			  CreateUserID VARCHAR (2) NULL ,
			  ModDate DATETIME NULL ,
			  ModUserID VARCHAR (2) NULL ,
			  PendUserGroup VARCHAR (12) NULL ,
			  DayBillCount INT NULL ,
			  TotalBillCount BIGINT NULL ,
			  ExportZeroAllowBills CHAR (1) NULL ,
			  CreateNF10s CHAR (1) NULL ,
			  PrintNF10Identifier CHAR (1) NULL ,
			  NF10FileFormat VARCHAR (3) NULL ,
			  EORFileFormat VARCHAR (3) NULL ,
			  PrintEORIdentifier CHAR (1) NULL ,
			  CreateEORWithNF10 CHAR (1) NULL ,
			  ExcludeAdjuster CHAR (1) NULL ,
			  ExcludeAttorney CHAR (1) NULL ,
			  ExcludeBranch CHAR (1) NULL ,
			  ExcludeClaim CHAR (1) NULL ,
			  ExcludeInsurer CHAR (1) NULL ,
			  ExcludePolicy CHAR (1) NULL ,
			  DaysPast SMALLINT NULL ,
			  EmailNotificationList VARCHAR (255) NULL ,
			  WFValidationFlag CHAR (1) NULL ,
			  PrintNF10ProvBillingAddr CHAR (1) NULL ,
			  BatchAckSLA INT NULL ,
			  DetailAckSLA INT NULL ,
			  ExportOtherBillingProvider CHAR (1) NULL ,
			  FormatRevenueCodes CHAR (1) NULL ,
			  CreateC8s CHAR (1) NULL ,
			  PrintC8Identifier CHAR (1) NULL ,
			  CreateEORWithC8 CHAR (1) NULL ,
			  NYProviderC81 CHAR (1) NULL ,
			  NYProviderC84 CHAR (1) NULL ,
			  NYProviderC8Identifier CHAR (1) NULL ,
			  NYProviderC8EOR CHAR (1) NULL ,
			  NYBoardC81 CHAR (1) NULL ,
			  NYBoardC84 CHAR (1) NULL ,
			  NYBoardC8Identifier CHAR (1) NULL ,
			  NYBoardC8EOR CHAR (1) NULL ,
			  NYClaimantC81 CHAR (1) NULL ,
			  NYClaimantC8Identifier CHAR (1) NULL ,
			  NYClaimantC8EOR CHAR (1) NULL ,
			  NYClaimantC8EORCover CHAR (1) NULL ,
			  NYAttorneyC81 CHAR (1) NULL ,
			  NYAttorneyC8Identifier CHAR (1) NULL ,
			  NYAttorneyC8EOR CHAR (1) NULL ,
			  NYAttorneyC8EORCover CHAR (1) NULL ,
			  NYProviderFormat VARCHAR (3) NULL ,
			  NYBoardFormat VARCHAR (3) NULL ,
			  NYClaimantFormat VARCHAR (3) NULL ,
			  NYAttorneyFormat VARCHAR (3) NULL ,
			  ExportPPOBillComment CHAR (1) NULL ,
			  IncludeNetwork CHAR (1) NULL ,
			  IncludeClaimUDF CHAR (1) NULL ,
			  IncludeProviderUDF CHAR (1) NULL ,
			  IncludeBillUDF CHAR (1) NULL ,
			  NetReevalFees CHAR (1) NULL ,
			  ExportCARCs CHAR (1) NULL ,
			  ExtendedHeader CHAR (1) NULL ,
			  ExtendedTrailer CHAR (1) NULL ,
			  SubmissionReasonCode VARCHAR (50) NULL ,
			  IncludeBillAttachment CHAR (1) NULL ,
			  UseExtendedLayout VARCHAR (120) NULL ,
			  ExcludeBillAttachment VARCHAR (500) NULL ,
			  ExportDiaryNotes CHAR (1) NULL ,
			  UpdateZABillControltoAccepted CHAR (1) NULL ,
			  UpdateZAPaidDateToPostDate CHAR (1) NULL ,
			  SetZAPaidDateToPostDateDays INT NULL ,
			  IncludeAdjusterUDF CHAR (1) NULL ,
			  IncludePolicyUDF CHAR (1) NULL ,
			  ExportZeroAllowReevals CHAR (1) NULL ,
			  UpdateREVALBillControlToAccepted CHAR (1) NULL ,
			  UpdateREVALPaidDateToPostDate CHAR (1) NULL ,
			  SetREVALPaidDateToPostDateDays INT NULL ,
			  ReductionsPerEORProfile CHAR (1) NULL ,
			  IncludeBillImage CHAR (1) NULL ,
			  NYClaimantC84 CHAR (1) NULL ,
			  NYAttorneyC84 CHAR (1) NULL ,
			  EDIJurisdiction VARCHAR(20) NULL ,

 ) ON DP_Ods_PartitionScheme(OdsCustomerId) 
 WITH (
       DATA_COMPRESSION = PAGE); 

     ALTER TABLE src.EDIControl ADD 
     CONSTRAINT PK_EDIControl PRIMARY KEY CLUSTERED (OdsPostingGroupAuditId, OdsCustomerId, EDIControlSeq) WITH (DATA_COMPRESSION = PAGE) ON
     DP_Ods_PartitionScheme(OdsCustomerId);

     ALTER INDEX PK_EDIControl ON src.EDIControl   REBUILD WITH(STATISTICS_INCREMENTAL = ON); 
 END 
 GO
IF NOT EXISTS ( SELECT  1
				FROM    sys.columns  
				WHERE   object_id = OBJECT_ID(N'src.EDIControl')
						AND NAME = 'EDIJurisdiction' )
	BEGIN
		ALTER TABLE src.EDIControl ADD EDIJurisdiction VARCHAR(20) NULL ;
	END ; 
GO



