IF OBJECT_ID('src.UserInfo', 'U') IS NULL 
	BEGIN
		CREATE TABLE src.UserInfo
			(
			  OdsPostingGroupAuditId INT NOT NULL ,  
			  OdsCustomerId INT NOT NULL , 
			  OdsCreateDate DATETIME2(7) NOT NULL ,
			  OdsSnapshotDate DATETIME2(7) NOT NULL , 
			  OdsRowIsCurrent BIT NOT NULL ,
			  OdsHashbytesValue VARBINARY(8000) NULL ,
			  DmlOperation CHAR(1) NOT NULL ,  
			  UserID CHAR (2) NOT NULL ,
			  UserPassword VARCHAR (35) NULL ,
			  Name VARCHAR (30) NULL ,
			  SecurityLevel CHAR (1) NULL ,
			  EnableAdjusterMenu CHAR (1) NULL ,
			  EnableProvAdds CHAR (1) NULL ,
			  AllowPosting CHAR (1) NULL ,
			  EnableClaimAdds CHAR (1) NULL ,
			  EnablePolicyAdds CHAR (1) NULL ,
			  EnableInvoiceCreditVoid CHAR (1) NULL ,
			  EnableReevaluations CHAR (1) NULL ,
			  EnablePPOAccess CHAR (1) NULL ,
			  EnableURCommentView CHAR (1) NULL ,
			  EnablePendRelease CHAR (1) NULL ,
			  EnableXtableUpdate CHAR (1) NULL ,
			  CreateUserID CHAR (2) NULL ,
			  CreateDate DATETIME NULL ,
			  ModUserID CHAR (2) NULL ,
			  ModDate DATETIME NULL ,
			  EnablePPOFastMatchAdds CHAR (1) NULL ,
			  ExternalID VARCHAR (30) NULL ,
			  EmailAddress VARCHAR (255) NULL ,
			  EmailNotify CHAR (1) NULL ,
			  ActiveStatus CHAR (1) NULL ,
			  CompanySeq SMALLINT NULL ,
			  NetworkLogin VARCHAR (50) NULL ,
			  AutomaticNetworkLogin CHAR (1) NULL ,
			  LastLoggedInDate DATETIME NULL ,
			  PromptToCreateMCC CHAR (1) NULL ,
			  AccessAllWorkQueues CHAR (1) NULL ,
			  LandingZoneAccess CHAR (1) NULL ,
			  ReviewLevel TINYINT NULL ,
			  EnableUserMaintenance CHAR (1) NULL ,
			  EnableHistoryMaintenance CHAR (1) NULL ,
			  EnableClientMaintenance CHAR (1) NULL ,
			  FeeAccess CHAR (1) NULL ,
			  EnableSalesTaxMaintenance CHAR (1) NULL ,
			  BESalesTaxZipCodeAccess CHAR (1) NULL ,
			  InvoiceGenAccess CHAR (1) NULL ,
			  BEPermitAllowOver CHAR (1) NULL ,
			  PermitRereviews CHAR (1) NULL ,
			  EditBillControl CHAR (1) NULL ,
			  RestrictEORNotes CHAR (1) NULL ,
			  UWQAutoNextBill CHAR (1) NULL ,
			  UWQDisableOptions CHAR (1) NULL ,
			  UWQDisableRules CHAR (1) NULL ,
			  PermitCheckReissue CHAR (1) NULL ,
			  EnableEDIAutomationMaintenance CHAR (1) NULL ,
			  RestrictDiaryNotes CHAR (1) NULL ,
			  RestrictExternalDiaryNotes CHAR (1) NULL ,
			  BEDeferManualModeMsg CHAR (1) NULL ,
			  UserRoleID INT NULL ,
			  EraseBillTempHistory CHAR (1) NULL ,
			  EditPPOProfile CHAR (1) NULL ,
			  EnableUrAccess CHAR (1) NULL ,
			  CapstoneConfigurationAccess CHAR (1) NULL ,
			  PermitUDFDefinition CHAR (1) NULL ,
			  EnablePPOProfileEdit CHAR (1) NULL ,
			  EnableSupervisorRole CHAR (1) NULL ,
 ) ON DP_Ods_PartitionScheme(OdsCustomerId) 
 WITH (
       DATA_COMPRESSION = PAGE); 

     ALTER TABLE src.UserInfo ADD 
     CONSTRAINT PK_UserInfo PRIMARY KEY CLUSTERED (OdsPostingGroupAuditId, OdsCustomerId, UserID) WITH (DATA_COMPRESSION = PAGE) ON
     DP_Ods_PartitionScheme(OdsCustomerId);

     ALTER INDEX PK_UserInfo ON src.UserInfo   REBUILD WITH(STATISTICS_INCREMENTAL = ON); 
 END 
 GO
