IF OBJECT_ID('stg.PPOContract', 'U') IS NOT NULL 
	DROP TABLE stg.PPOContract  
BEGIN
	CREATE TABLE stg.PPOContract
		(
		  PPONetworkID CHAR (2) NULL,
		  PPOContractID VARCHAR (30) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
		  SiteCode CHAR (3) NULL,
		  TIN VARCHAR (9) NULL,
		  AlternateTIN VARCHAR (9) NULL,
		  StartDate DATETIME NULL,
		  EndDate DATETIME NULL,
		  OPLineItemDefaultDiscount SMALLINT NULL,
		  CompanyName VARCHAR (35) NULL,
		  First VARCHAR (35) NULL,
		  GroupCode CHAR (3) NULL,
		  GroupName VARCHAR (40) NULL,
		  OPDiscountBaseValue CHAR (1) NULL,
		  OPOffFS SMALLINT NULL,
		  OPOffUCR SMALLINT NULL,
		  OPOffCharge SMALLINT NULL,
		  OPEffectiveDate DATETIME NULL,
		  OPAdditionalDiscountOffLink SMALLINT NULL,
		  OPTerminationDate DATETIME NULL,
		  OPUCRPercentile SMALLINT NULL,
		  OPCondition CHAR (2) NULL,
		  IPDiscountBaseValue CHAR (1) NULL,
		  IPOffFS SMALLINT NULL,
		  IPOffUCR SMALLINT NULL,
		  IPOffCharge SMALLINT NULL,
		  IPEffectiveDate DATETIME NULL,
		  IPTerminationDate DATETIME NULL,
		  IPCondition CHAR (2) NULL,
		  IPStopCapAmount MONEY NULL,
		  IPStopCapRate SMALLINT NULL,
		  MinDisc SMALLMONEY NULL,
		  MaxDisc SMALLMONEY NULL,
		  MedicalPerdiem SMALLMONEY NULL,
		  SurgicalPerdiem SMALLMONEY NULL,
		  ICUPerdiem SMALLMONEY NULL,
		  PsychiatricPerdiem SMALLMONEY NULL,
		  MiscParm CHAR (2) NULL,
		  SpcCode CHAR (1) NULL,
		  PPOType CHAR (1) NULL,
		  BillingAddress1 VARCHAR (30) NULL,
		  BillingAddress2 VARCHAR (30) NULL,
		  BillingCity VARCHAR (20) NULL,
		  BillingState CHAR (2) NULL,
		  BillingZip VARCHAR (9) NULL,
		  PracticeAddress1 VARCHAR (30) NULL,
		  PracticeAddress2 VARCHAR (30) NULL,
		  PracticeCity VARCHAR (20) NULL,
		  PracticeState CHAR (2) NULL,
		  PracticeZip VARCHAR (9) NULL,
		  PhoneNum VARCHAR (10) NULL,
		  OutFile VARCHAR (12) NULL,
		  InpatFile VARCHAR (12) NULL,
		  URCoordinatorFlag CHAR (1) NULL,
		  ExclusivePPOOrgFlag CHAR (1) NULL,
		  StopLossTypeCode VARCHAR (4) NULL,
		  BR_RNEDiscount SMALLINT NULL,
		  ModDate DATETIME NULL,
		  ExportFlag CHAR (1) NULL,
		  OPManualIndicator CHAR (1) NULL,
		  OPStopCapAmount MONEY NULL,
		  OPStopCapRate SMALLINT NULL,
		  Specialty1 VARCHAR (4) NULL,
		  Specialty2 VARCHAR (4) NULL,
		  LessorOfThreshold SMALLINT NULL,
		  BilateralDiscount SMALLINT NULL,
		  SurgeryDiscount2 SMALLINT NULL,
		  SurgeryDiscount3 SMALLINT NULL,
		  SurgeryDiscount4 SMALLINT NULL,
		  SurgeryDiscount5 SMALLINT NULL,
		  Matrix CHAR (1) NULL,
		  ProvType VARCHAR (5) NULL,
		  AllInclusive CHAR (1) NULL,
		  Region VARCHAR (4) NULL,
		  PaymentAddressFlag CHAR (1) NULL,
		  MedicalGroup CHAR (1) NULL,
		  MedicalGroupCode VARCHAR (4) NULL,
		  RateMode CHAR (1) NULL,
		  PracticeCounty VARCHAR (25) NULL,
		  FIPSCountyCode CHAR (3) NULL,
		  PrimaryCareFlag CHAR (1) NULL,
		  PPOContractIDOld VARCHAR (14) NULL,
		  MultiSurg CHAR (1) NULL,
		  BiLevel CHAR (1) NULL,
		  DRGRate SMALLMONEY NULL,
		  DRGGreaterThanBC SMALLINT NULL,
		  DRGMinPercentBC SMALLINT NULL,
		  CarveOut CHAR (1) NULL,
		  PPOtoFSSeq INT NULL,
		  LicenseNum VARCHAR (30) NULL,
		  MedicareNum VARCHAR (20) NULL,
		  NPI VARCHAR (10) NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

