IF OBJECT_ID('stg.Claim', 'U') IS NOT NULL 
	DROP TABLE stg.Claim  
BEGIN
	CREATE TABLE stg.Claim
		(
		  ClaimSysSubSet CHAR (4) NULL,
		  ClaimSeq INT NULL,
		  ClaimID VARCHAR (35) NULL,
		  DOI DATETIME NULL,
		  PatientSSN VARCHAR (9) NULL,
		  PatientFirstName VARCHAR (10) NULL,
		  PatientLastName VARCHAR (20) NULL,
		  PatientMInitial CHAR (1) NULL,
		  ExternalClaimID VARCHAR (35) NULL,
		  PolicyCoPayAmount MONEY NULL,
		  PolicyCoPayPct SMALLINT NULL,
		  PolicyDeductible MONEY NULL,
		  Status CHAR (1) NULL,
		  PolicyLimit MONEY NULL,
		  PolicyID VARCHAR (30) NULL,
		  PolicyTimeLimit SMALLINT NULL,
		  Adjuster VARCHAR (25) NULL,
		  PolicyLimitWarningPct SMALLINT NULL,
		  FirstDOS DATETIME NULL,
		  LastDOS DATETIME NULL,
		  LoadDate DATETIME NULL,
		  ModDate DATETIME NULL,
		  ModUserID CHAR (2) NULL,
		  PatientSex CHAR (1) NULL,
		  PatientCity VARCHAR (20) NULL,
		  PatientDOB DATETIME NULL,
		  PatientStreet2 VARCHAR (30) NULL,
		  PatientState CHAR (2) NULL,
		  PatientZip VARCHAR (9) NULL,
		  PatientStreet1 VARCHAR (30) NULL,
		  MMIDate DATETIME NULL,
		  BodyPart1 CHAR (3) NULL,
		  BodyPart2 CHAR (3) NULL,
		  BodyPart3 CHAR (3) NULL,
		  BodyPart4 CHAR (3) NULL,
		  BodyPart5 CHAR (3) NULL,
		  Location VARCHAR (10) NULL,
		  NatureInj CHAR (3) NULL,
		  URFlag CHAR (1) NULL,
		  CarKnowDate DATETIME NULL,
		  ClaimType CHAR (2) NULL,
		  CtrlDay SMALLINT NULL,
		  MCOChoice CHAR (2) NULL,
		  ClientCodeDefault VARCHAR (4) NULL,
		  CloseDate DATETIME NULL,
		  ReopenDate DATETIME NULL,
		  MedCloseDate DATETIME NULL,
		  MedStipDate DATETIME NULL,
		  LegalStatus1 CHAR (2) NULL,
		  LegalStatus2 CHAR (2) NULL,
		  LegalStatus3 CHAR (2) NULL,
		  Jurisdiction CHAR (2) NULL,
		  ProductCode CHAR (1) NULL,
		  PlaintiffAttorneySeq BIGINT NULL,
		  DefendantAttorneySeq BIGINT NULL,
		  BranchID VARCHAR (20) NULL,
		  OccCode CHAR (2) NULL,
		  ClaimSeverity CHAR (2) NULL,
		  DateLostBegan DATETIME NULL,
		  AccidentEmployment CHAR (1) NULL,
		  RelationToInsured CHAR (1) NULL,
		  Policy5Days CHAR (2) NULL,
		  Policy90Days CHAR (2) NULL,
		  Job5Days CHAR (2) NULL,
		  Job90Days CHAR (2) NULL,
		  LostDays SMALLINT NULL,
		  ActualRTWDate DATETIME NULL,
		  MCOTransInd CHAR (2) NULL,
		  QualifiedInjWorkInd CHAR (2) NULL,
		  PermStationaryInd CHAR (2) NULL,
		  HospitalAdmit CHAR (2) NULL,
		  QualifiedInjWorkDate DATETIME NULL,
		  RetToWorkDate DATETIME NULL,
		  PermStationaryDate DATETIME NULL,
		  MCOFein VARCHAR (9) NULL,
		  CreateUserID CHAR (2) NULL,
		  IDCode VARCHAR (80) NULL,
		  IDType VARCHAR (2) NULL,
		  MPNOptOutEffectiveDate DATETIME NULL,
		  MPNOptOutTerminationDate DATETIME NULL,
		  MPNOptOutPhysicianName VARCHAR (50) NULL,
		  MPNOptOutPhysicianTIN VARCHAR (9) NULL,
		  MPNChoice CHAR (2) NULL,
		  JurisdictionClaimID VARCHAR (35) NULL,
		  PolicyLimitResult CHAR (1) NULL,
		  PatientPrimaryPhone VARCHAR (20) NULL,
		  PatientWorkPhone VARCHAR (20) NULL,
		  PatientAlternatePhone VARCHAR (20) NULL,
		  ICDVersion SMALLINT NULL,
		  LastDateofTrauma DATETIME NULL,
		  ClaimAdminClaimNum VARCHAR (35) NULL,
		  PatientCountryCode CHAR (3) NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

