IF OBJECT_ID('stg.EDIXmitBill', 'U') IS NOT NULL 
	DROP TABLE stg.EDIXmitBill  
BEGIN
	CREATE TABLE stg.EDIXmitBill
		(
		  EDIXmitBillSeq INT NULL,
		  EDIXmitSeq INT NULL,
		  EDIHistoryProviderSeq INT NULL,
		  EDIHistoryClaimSeq INT NULL,
		  EDIHistoryInsurerSeq INT NULL,
		  EDIControlSeq INT NULL,
		  ClientCode CHAR (4) NULL,
		  BillSeq INT NULL,
		  Jurisdiction CHAR (2) NULL,
		  TOB CHAR (1) NULL,
		  UB92TOB CHAR (10) NULL,
		  BillSeqOrgRev INT NULL,
		  TotalCharge MONEY NULL,
		  BillableLines INT NULL,
		  PaidDate DATETIME NULL,
		  PaidAmount MONEY NULL,
		  DRG CHAR (3) NULL,
		  PatientStatus CHAR (2) NULL,
		  PostDate DATETIME NULL,
		  DocCtrlID VARCHAR (50) NULL,
		  DOSFirst DATETIME NULL,
		  DOSLast DATETIME NULL,
		  PPONetworkID CHAR (2) NULL,
		  PPOContractID VARCHAR (30) NULL,
		  Adjuster VARCHAR (25) NULL,
		  CarrierSeqNew VARCHAR (30) NULL,
		  ProvInvoice VARCHAR (14) NULL,
		  ProvSpecialty1 VARCHAR (10) NULL,
		  ClientTOB VARCHAR (5) NULL,
		  SubProductCode CHAR (1) NULL,
		  DupClientCode CHAR (4) NULL,
		  DupBillSeq INT NULL,
		  ConsultDate DATETIME NULL,
		  AdmitDate DATETIME NULL,
		  DischargeDate DATETIME NULL,
		  SubmitDate DATETIME NULL,
		  RcvdDate DATETIME NULL,
		  RcvdBrDate DATETIME NULL,
		  ReviewDate DATETIME NULL,
		  DueDate DATETIME NULL,
		  PmtAuth VARCHAR (4) NULL,
		  ForcePay CHAR (1) NULL,
		  ProvLicenseNum VARCHAR (30) NULL,
		  CreateUserID VARCHAR (2) NULL,
		  ModUserID VARCHAR (2) NULL,
		  PatientAccount VARCHAR (20) NULL,
		  RefProvName VARCHAR (40) NULL,
		  ProvType CHAR (3) NULL,
		  DOI DATETIME NULL,
		  GeoState CHAR (2) NULL,
		  ManualReductionMode SMALLINT NULL,
		  PPONetworkJurisdictionInd CHAR (1) NULL,
		  PPONetworkJurisdictionInsurerSeq INT NULL,
		  WFQueueParameter1 VARCHAR (35) NULL,
		  CheckNum VARCHAR (30) NULL,
		  ExternalID VARCHAR (50) NULL,
		  EDITestIndicator CHAR (1) NULL,
		  ICDVersion SMALLINT NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

