IF OBJECT_ID('stg.Line', 'U') IS NOT NULL 
	DROP TABLE stg.Line  
BEGIN
	CREATE TABLE stg.Line
		(
		  ClientCode CHAR (4) NULL,
		  BillSeq INT NULL,
		  LineSeq SMALLINT NULL,
		  DupClientCode CHAR (4) NULL,
		  DupBillSeq INT NULL,
		  DOS DATETIME NULL,
		  ProcType CHAR (1) NULL,
		  PPOOverride MONEY NULL,
		  ClientLineType VARCHAR (5) NULL,
		  ProvType CHAR (3) NULL,
		  URQtyAllow SMALLINT NULL,
		  URQtySvd SMALLINT NULL,
		  DOSTo DATETIME NULL,
		  URAllow MONEY NULL,
		  URCaseSeq INT NULL,
		  RevenueCode CHAR (4) NULL,
		  ProcBilled VARCHAR (30) NULL,
		  URReviewSeq SMALLINT NULL,
		  URPriority SMALLINT NULL,
		  ProcCode VARCHAR (30) NULL,
		  Units DECIMAL (11,3) NULL,
		  AllowUnits DECIMAL (11,3) NULL,
		  Charge MONEY NULL,
		  BRAllow MONEY NULL,
		  PPOAllow MONEY NULL,
		  PayOverride MONEY NULL,
		  ProcNew VARCHAR (30) NULL,
		  AdjAllow MONEY NULL,
		  ReevalAmount MONEY NULL,
		  POS CHAR (2) NULL,
		  DxRefList VARCHAR (30) NULL,
		  TOS CHAR (2) NULL,
		  ReevalTxtPtr SMALLINT NULL,
		  FSAmount MONEY NULL,
		  UCAmount MONEY NULL,
		  CoPay MONEY NULL,
		  Deductible MONEY NULL,
		  CostToChargeRatio FLOAT NULL,
		  RXNumber VARCHAR (20) NULL,
		  DaysSupply SMALLINT NULL,
		  DxRef VARCHAR (4) NULL,
		  ExternalID VARCHAR (30) NULL,
		  ItemCostInvoiced MONEY NULL,
		  ItemCostAdditional MONEY NULL,
		  Refill CHAR (1) NULL,
		  ProvSecondaryID VARCHAR (30) NULL,
		  Certification CHAR (1) NULL,
		  ReevalTxtSrc VARCHAR (3) NULL,
		  BasisOfCost CHAR (1) NULL,
		  DMEFrequencyCode CHAR (1) NULL,
		  ProvRenderingNPI VARCHAR (10) NULL,
		  ProvSecondaryIDQualifier CHAR (2) NULL,
		  PaidProcCode VARCHAR (30) NULL,
		  PaidProcType VARCHAR (3) NULL,
		  URStatus CHAR (1) NULL,
		  URWorkflowStatus CHAR (1) NULL,
		  OverrideAllowUnits DECIMAL (11,3) NULL,
		  LineSeqOrgRev SMALLINT NULL,
		  ODGFlag SMALLINT NULL,
		  CompoundDrugIndicator CHAR (1) NULL,
		  PriorAuthNum VARCHAR (50) NULL,
		  ReevalParagraphJurisdiction CHAR (2) NULL,
		  DmlOperation CHAR(1) NOT NULL 
		 )
END 
GO

