IF OBJECT_ID('dbo.if_EDIControl', 'IF') IS NOT NULL
    DROP FUNCTION dbo.if_EDIControl;
GO

CREATE FUNCTION dbo.if_EDIControl(
	@OdsPostingGroupAuditId INT
)
RETURNS TABLE
AS
RETURN
SELECT 
	 t.OdsPostingGroupAuditId,
	t.OdsCustomerId,
	t.OdsCreateDate,
	t.OdsSnapshotDate,
	t.OdsRowIsCurrent,
	t.OdsHashbytesValue,
	t.DmlOperation,
	t.EDIControlSeq,
	t.EDIMapToolSiteCode,
	t.EDIPortType,
	t.EDIMapToolID,
	t.Name,
	t.LastTapeDate,
	t.LastStartDate,
	t.LastEndDate,
	t.DayCounter,
	t.TotalCounter,
	t.VendorNum,
	t.VendorContact,
	t.VendorPhone,
	t.AccountNum,
	t.OfficeNum,
	t.EDISenderQualifier,
	t.EDISenderIdentifier,
	t.EDIReceiverQualifier,
	t.EDIReceiverIdentifier,
	t.EDIAcknowledgement,
	t.EDITestIndicator,
	t.ExportCredits,
	t.ExportNegatives,
	t.CreateEORs,
	t.SpecialProcessFlag,
	t.ARCompany,
	t.ARContact,
	t.ARAddr1,
	t.ARAddr2,
	t.ARCity,
	t.ARState,
	t.ARZip,
	t.ARPhone,
	t.EDISenderZIP,
	t.EDIReceiverZIP,
	t.CreateDate,
	t.CreateUserID,
	t.ModDate,
	t.ModUserID,
	t.PendUserGroup,
	t.DayBillCount,
	t.TotalBillCount,
	t.ExportZeroAllowBills,
	t.CreateNF10s,
	t.PrintNF10Identifier,
	t.NF10FileFormat,
	t.EORFileFormat,
	t.PrintEORIdentifier,
	t.CreateEORWithNF10,
	t.ExcludeAdjuster,
	t.ExcludeAttorney,
	t.ExcludeBranch,
	t.ExcludeClaim,
	t.ExcludeInsurer,
	t.ExcludePolicy,
	t.DaysPast,
	t.EmailNotificationList,
	t.WFValidationFlag,
	t.PrintNF10ProvBillingAddr,
	t.BatchAckSLA,
	t.DetailAckSLA,
	t.ExportOtherBillingProvider,
	t.FormatRevenueCodes,
	t.CreateC8s,
	t.PrintC8Identifier,
	t.CreateEORWithC8,
	t.NYProviderC81,
	t.NYProviderC84,
	t.NYProviderC8Identifier,
	t.NYProviderC8EOR,
	t.NYBoardC81,
	t.NYBoardC84,
	t.NYBoardC8Identifier,
	t.NYBoardC8EOR,
	t.NYClaimantC81,
	t.NYClaimantC8Identifier,
	t.NYClaimantC8EOR,
	t.NYClaimantC8EORCover,
	t.NYAttorneyC81,
	t.NYAttorneyC8Identifier,
	t.NYAttorneyC8EOR,
	t.NYAttorneyC8EORCover,
	t.NYProviderFormat,
	t.NYBoardFormat,
	t.NYClaimantFormat,
	t.NYAttorneyFormat,
	t.ExportPPOBillComment,
	t.IncludeNetwork,
	t.IncludeClaimUDF,
	t.IncludeProviderUDF,
	t.IncludeBillUDF,
	t.NetReevalFees,
	t.ExportCARCs,
	t.ExtendedHeader,
	t.ExtendedTrailer,
	t.SubmissionReasonCode,
	t.IncludeBillAttachment,
	t.UseExtendedLayout,
	t.ExcludeBillAttachment,
	t.ExportDiaryNotes,
	t.UpdateZABillControltoAccepted,
	t.UpdateZAPaidDateToPostDate,
	t.SetZAPaidDateToPostDateDays,
	t.IncludeAdjusterUDF,
	t.IncludePolicyUDF,
	t.ExportZeroAllowReevals,
	t.UpdateREVALBillControlToAccepted,
	t.UpdateREVALPaidDateToPostDate,
	t.SetREVALPaidDateToPostDateDays,
	t.ReductionsPerEORProfile,
	t.IncludeBillImage,
	t.NYClaimantC84,
	t.NYAttorneyC84,
	t.EDIJurisdiction
FROM src.EDIControl t
INNER JOIN (
	SELECT 
		OdsCustomerId,
		EDIControlSeq,
		MAX(OdsPostingGroupAuditId) AS OdsPostingGroupAuditId
	FROM src.EDIControl
	WHERE OdsPostingGroupAuditId <= @OdsPostingGroupAuditId
	GROUP BY OdsCustomerId,
		EDIControlSeq) s
ON t.OdsPostingGroupAuditId = s.OdsPostingGroupAuditId
	AND t.OdsCustomerId = s.OdsCustomerId
	AND t.EDIControlSeq = s.EDIControlSeq
WHERE t.DmlOperation <> 'D';

GO


