IF OBJECT_ID('dbo.if_Client', 'IF') IS NOT NULL
    DROP FUNCTION dbo.if_Client;
GO

CREATE FUNCTION dbo.if_Client(
	@OdsPostingGroupAuditId INT
)
RETURNS TABLE
AS
RETURN
SELECT 
	 t.OdsPostingGroupAuditId,
	t.OdsCustomerId,
	t.OdsCreateDate,
	t.OdsSnapshotDate,
	t.OdsRowIsCurrent,
	t.OdsHashbytesValue,
	t.DmlOperation,
	t.ClientCode,
	t.Name,
	t.Jurisdiction,
	t.ControlNum,
	t.PolicyTimeLimit,
	t.PolicyLimitWarningPct,
	t.PolicyLimit,
	t.PolicyDeductible,
	t.PolicyCoPayPct,
	t.PolicyCoPayAmount,
	t.BEDiagnosis,
	t.InvoiceBRCycle,
	t.Status,
	t.InvoiceGroupBy,
	t.BEDOI,
	t.DrugMarkUpBrand,
	t.SupplyLimit,
	t.InvoicePPOCycle,
	t.InvoicePPOTax,
	t.DrugMarkUpGen,
	t.DrugDispGen,
	t.DrugDispBrand,
	t.BEAdjuster,
	t.InvoiceTax,
	t.CompanySeq,
	t.BEMedAlert,
	t.UCRPercentile,
	t.ClientComment,
	t.RemitAttention,
	t.RemitAddress1,
	t.RemitAddress2,
	t.RemitCityStateZip,
	t.RemitPhone,
	t.ExternalID,
	t.BEOther,
	t.MedAlertDays,
	t.MedAlertVisits,
	t.MedAlertMaxCharge,
	t.MedAlertWarnVisits,
	t.ProviderSubSet,
	t.AllowReReview,
	t.AcctRep,
	t.ClientType,
	t.UCRMarkUp,
	t.InvoiceCombined,
	t.BESubmitDt,
	t.BERcvdCarrierDate,
	t.BERcvdBillReviewDate,
	t.BEDueDate,
	t.ProductCode,
	t.BEProvInvoice,
	t.ClaimSysSubSet,
	t.DefaultBRtoUCR,
	t.BasePPOFeesOffFS,
	t.BEClientTOBTableCode,
	t.BEForcePay,
	t.BEPayAuthorization,
	t.BECarrierSeqFlag,
	t.BEProvTypeTableCode,
	t.BEProvSpcl1TableCode,
	t.BEProvLicense,
	t.BEPayAuthTableCode,
	t.PendReasonTableCode,
	t.VocRehab,
	t.EDIAckRequired,
	t.StateRptInd,
	t.BEPatientAcctNum,
	t.AutoDup,
	t.UseAllowOnDup,
	t.URImportUsed,
	t.URProgStartDate,
	t.URImportCtrlNum,
	t.URImportCtrlGroup,
	t.UCRSource,
	t.UCRMarkup2,
	t.NGDTableCode,
	t.BESubProductTableCode,
	t.CountryTableCode,
	t.BERefPhys,
	t.BEPmtWarnDays,
	t.GeoState,
	t.BEDisableDOICheck,
	t.DelayDays,
	t.BEValidateTotal,
	t.BEFastMatch,
	t.BEPriorBillDefault,
	t.BEClientDueDays,
	t.BEAutoCalcDueDate,
	t.UCRSource2,
	t.UCRPercentile2,
	t.BEProvSpcl2TableCode,
	t.FeeRateCntrlEx,
	t.FeeRateCntrlIn,
	t.BECollisionProvBills,
	t.BECollisionBills,
	t.SupplyMarkup,
	t.BECollisionProviders,
	t.DefaultCoPayDeduct,
	t.AutoBundling,
	t.BEValidateBillClaimICD9,
	t.EnableGenericReprice,
	t.BESubProdFeeInfo,
	t.DenyNonInjDrugs,
	t.BECollisionDosLines,
	t.PPOProfileSiteCode,
	t.PPOProfileID,
	t.BEShowDEAWarning,
	t.BEHideAdjusterColumn,
	t.BEHideCoPayColumn,
	t.BEHideDeductColumn,
	t.BEPaidDate,
	t.BEProcCrossWalk,
	t.CreateUserID,
	t.CreateDate,
	t.ModUserID,
	t.ModDate,
	t.BEConsultDate,
	t.BEShowPharmacyColumns,
	t.BEAdjVerifDates,
	t.FutureDOSMonthLimit,
	t.BEStopAtLineUnits,
	t.BENYNF10Fields,
	t.EnableDRGGrouper,
	t.ApplyCptAmaUcrRules,
	t.BEProvSigOnFile,
	t.BETimeEntry,
	t.SalesTaxExempt,
	t.InvoiceRetailProfile,
	t.InvoiceWholesaleProfile,
	t.BEDefaultTaxZip,
	t.ReceiptHandlingCode,
	t.PaymentHandlingCode,
	t.DefaultRetailSalesTaxZip,
	t.DefaultWholesaleSalesTaxZip,
	t.TxNonSubscrib,
	t.RootClaimLength,
	t.BEDAWTableCode,
	t.EORProfileSeq,
	t.BEOtherBillingProvider,
	t.BEDocCtrlID,
	t.ReportingETL,
	t.ClaimVerification,
	t.ProvVerification,
	t.BEPermitAllowOver,
	t.BEStopAtLineDxRef,
	t.BEQuickInfoCode,
	t.ExcludedSmartClientSelect,
	t.CollisionsSearchBy,
	t.AutoDupIncludeProv,
	t.URProfileID,
	t.ExcludeURDM,
	t.BECollisionURCases,
	t.MUEEdits,
	t.CPTRarity,
	t.ICDRarity,
	t.ICDToCPTRarity,
	t.BEDisablePPOSearch,
	t.BEShowLineExternalIDColumn,
	t.BEShowLinePriorAuthColumn,
	t.SmartGuidelinesFlag,
	t.BEProvBillingLicense,
	t.BEProvFacilityLicense,
	t.VendorProviderSubSet,
	t.DefaultJurisClientCode,
	t.ClientGroupId,
	t.DrugDispFeeApplyTo
FROM src.Client t
INNER JOIN (
	SELECT 
		OdsCustomerId,
		ClientCode,
		MAX(OdsPostingGroupAuditId) AS OdsPostingGroupAuditId
	FROM src.Client
	WHERE OdsPostingGroupAuditId <= @OdsPostingGroupAuditId
	GROUP BY OdsCustomerId,
		ClientCode) s
ON t.OdsPostingGroupAuditId = s.OdsPostingGroupAuditId
	AND t.OdsCustomerId = s.OdsCustomerId
	AND t.ClientCode = s.ClientCode
WHERE t.DmlOperation <> 'D';

GO


