IF OBJECT_ID('dbo.if_prf_Profile', 'IF') IS NOT NULL
    DROP FUNCTION dbo.if_prf_Profile;
GO

CREATE FUNCTION dbo.if_prf_Profile(
	@OdsPostingGroupAuditId INT
)
RETURNS TABLE
AS
RETURN
SELECT 
	 t.OdsPostingGroupAuditId,
	t.OdsCustomerId,
	t.OdsCreateDate,
	t.OdsSnapshotDate,
	t.OdsRowIsCurrent,
	t.OdsHashbytesValue,
	t.DmlOperation,
	t.ProfileId,
	t.OfficeId,
	t.CoverageId,
	t.StateId,
	t.AnHeader,
	t.AnFooter,
	t.ExHeader,
	t.ExFooter,
	t.AnalystEdits,
	t.DxEdits,
	t.DxNonTraumaDays,
	t.DxNonSpecDays,
	t.PrintCopies,
	t.NewPvdState,
	t.bDuration,
	t.bLimits,
	t.iDurPct,
	t.iLimitPct,
	t.PolicyLimit,
	t.CoPayPercent,
	t.CoPayMax,
	t.Deductible,
	t.PolicyWarn,
	t.PolicyWarnPerc,
	t.FeeSchedules,
	t.DefaultProfile,
	t.FeeAncillaryPct,
	t.iGapdol,
	t.iGapTreatmnt,
	t.bGapTreatmnt,
	t.bGapdol,
	t.bPrintAdjustor,
	t.sPrinterName,
	t.ErEdits,
	t.ErAllowedDays,
	t.UcrFsRules,
	t.LogoIdNo,
	t.LogoJustify,
	t.BillLine,
	t.Version,
	t.ClaimDeductible,
	t.IncludeCommitted,
	t.FLMedicarePercent,
	t.UseLevelOfServiceUrl,
	t.LevelOfServiceURL,
	t.CCIPrimary,
	t.CCISecondary,
	t.CCIMutuallyExclusive,
	t.CCIComprehensiveComponent,
	t.PayDRGAllowance,
	t.FLHospEmPriceOn,
	t.EnableBillRelease,
	t.DisableSubmitBill,
	t.MaxPaymentsPerBill,
	t.NoOfPmtPerBill,
	t.DefaultDueDate,
	t.CheckForNJCarePaths,
	t.NJCarePathPercentFS,
	t.ApplyEndnoteForNJCarePaths,
	t.FLMedicarePercent2008,
	t.RequireEndnoteDuringOverride,
	t.StorePerUnitFSandUCR,
	t.UseProviderNetworkEnrollment,
	t.UseASCRule,
	t.AsstCoSurgeonEligible,
	t.LastChangedOn,
	t.IsNJPhysMedCapAfterCTG,
	t.IsEligibleAmtFeeBased,
	t.HideClaimTreeTotalsGrid,
	t.SortBillsBy,
	t.SortBillsByOrder,
	t.ApplyNJEmergencyRoomBenchmarkFee,
	t.AllowIcd10ForNJCarePaths,
	t.EnableOverrideDeductible,
	t.AnalyzeDiagnosisPointers,
	t.MedicareFeePercent,
	t.EnableSupplementalNdcData,
	t.ApplyOriginalNdcAwp,
	t.NdcAwpNotAvailable,
	t.PayEapgAllowance,
	t.MedicareInpatientApcEnabled,
	t.MedicareOutpatientAscEnabled,
	t.MedicareAscEnabled,
	t.UseMedicareInpatientApcFee,
	t.MedicareInpatientDrgEnabled,
	t.MedicareInpatientDrgPricingType,
	t.MedicarePhysicianEnabled,
	t.MedicareAmbulanceEnabled,
	t.MedicareDmeposEnabled,
	t.MedicareAspDrugAndClinicalEnabled,
	t.MedicareInpatientPricingType,
	t.MedicareOutpatientPricingRulesEnabled,
	t.MedicareAscPricingRulesEnabled,
	t.NjUseAdmitTypeEnabled,
	t.MedicareClinicalLabEnabled,
	t.MedicareInpatientEnabled,
	t.MedicareOutpatientApcEnabled,
	t.MedicareAspDrugEnabled,
	t.ShowAllocationsOnEob,
	t.EmergencyCarePricingRuleId,
	t.OutOfStatePricingEffectiveDateId,
	t.PreAllocation,
	t.AssistantCoSurgeonModifiers,
	t.AssistantSurgeryModifierNotMedicallyNecessary,
	t.AssistantSurgeryModifierRequireAdditionalDocument,
	t.CoSurgeryModifierNotMedicallyNecessary,
	t.CoSurgeryModifierRequireAdditionalDocument,
	t.DxNoDiagnosisDays,
	t.ModifierExempted
FROM src.prf_Profile t
INNER JOIN (
	SELECT 
		OdsCustomerId,
		ProfileId,
		MAX(OdsPostingGroupAuditId) AS OdsPostingGroupAuditId
	FROM src.prf_Profile
	WHERE OdsPostingGroupAuditId <= @OdsPostingGroupAuditId
	GROUP BY OdsCustomerId,
		ProfileId) s
ON t.OdsPostingGroupAuditId = s.OdsPostingGroupAuditId
	AND t.OdsCustomerId = s.OdsCustomerId
	AND t.ProfileId = s.ProfileId
WHERE t.DmlOperation <> 'D';

GO


