IF OBJECT_ID('dbo.if_Esp_Ppo_Billing_Data_Self_Bill', 'IF') IS NOT NULL
    DROP FUNCTION dbo.if_Esp_Ppo_Billing_Data_Self_Bill;
GO

CREATE FUNCTION dbo.if_Esp_Ppo_Billing_Data_Self_Bill(
	@OdsPostingGroupAuditId INT
)
RETURNS TABLE
AS
RETURN
SELECT 
	 t.OdsPostingGroupAuditId,
	t.OdsCustomerId,
	t.OdsCreateDate,
	t.OdsSnapshotDate,
	t.OdsRowIsCurrent,
	t.OdsHashbytesValue,
	t.DmlOperation,
	t.COMPANYCODE,
	t.TRANSACTIONTYPE,
	t.BILL_HDR_AMTALLOWED,
	t.BILL_HDR_AMTCHARGED,
	t.BILL_HDR_BILLIDNO,
	t.BILL_HDR_CMT_HDR_IDNO,
	t.BILL_HDR_CREATEDATE,
	t.BILL_HDR_CV_TYPE,
	t.BILL_HDR_FORM_TYPE,
	t.BILL_HDR_NOLINES,
	t.BILLS_ALLOWED,
	t.BILLS_ANALYZED,
	t.BILLS_CHARGED,
	t.BILLS_DT_SVC,
	t.BILLS_LINE_NO,
	t.CLAIMANT_CLIENTREF_CMTSUFFIX,
	t.CLAIMANT_CMTFIRST_NAME,
	t.CLAIMANT_CMTIDNO,
	t.CLAIMANT_CMTLASTNAME,
	t.CMTSTATEOFJURISDICTION,
	t.CLAIMS_COMPANYID,
	t.CLAIMS_CLAIMNO,
	t.CLAIMS_DATELOSS,
	t.CLAIMS_OFFICEINDEX,
	t.CLAIMS_POLICYHOLDERSNAME,
	t.CLAIMS_POLICYNUMBER,
	t.PNETWKEVENTLOG_EVENTID,
	t.PNETWKEVENTLOG_LOGDATE,
	t.PNETWKEVENTLOG_NETWORKID,
	t.ACTIVITY_FLAG,
	t.PPO_AMTALLOWED,
	t.PREPPO_AMTALLOWED,
	t.PREPPO_ALLOWED_FS,
	t.PRF_COMPANY_COMPANYNAME,
	t.PRF_OFFICE_OFCNAME,
	t.PRF_OFFICE_OFCNO,
	t.PROVIDER_PVDFIRSTNAME,
	t.PROVIDER_PVDGROUP,
	t.PROVIDER_PVDLASTNAME,
	t.PROVIDER_PVDTIN,
	t.PROVIDER_STATE,
	t.UDFCLAIM_UDFVALUETEXT,
	t.ENTRY_DATE,
	t.UDFCLAIMANT_UDFVALUETEXT,
	t.SOURCE_DB,
	t.CLAIMS_CV_CODE,
	t.VPN_TRANSACTIONID,
	t.VPN_TRANSACTIONTYPEID,
	t.VPN_BILLIDNO,
	t.VPN_LINE_NO,
	t.VPN_CHARGED,
	t.VPN_DPALLOWED,
	t.VPN_VPNALLOWED,
	t.VPN_SAVINGS,
	t.VPN_CREDITS,
	t.VPN_HASOVERRIDE,
	t.VPN_ENDNOTES,
	t.VPN_NETWORKIDNO,
	t.VPN_PROCESSFLAG,
	t.VPN_LINETYPE,
	t.VPN_DATETIMESTAMP,
	t.VPN_SEQNO,
	t.VPN_VPN_REF_LINE_NO,
	t.VPN_NETWORKNAME,
	t.VPN_SOJ,
	t.VPN_CAT3,
	t.VPN_PPODATESTAMP,
	t.VPN_NINTEYDAYS,
	t.VPN_BILL_TYPE,
	t.VPN_NET_SAVINGS,
	t.CREDIT,
	t.RECON,
	t.DELETED,
	t.STATUS_FLAG,
	t.DATE_SAVED,
	t.SUB_NETWORK,
	t.INVALID_CREDIT,
	t.PROVIDER_SPECIALTY,
	t.ADJUSTOR_IDNUMBER,
	t.ACP_FLAG,
	t.OVERRIDE_ENDNOTES,
	t.OVERRIDE_ENDNOTES_DESC
FROM src.Esp_Ppo_Billing_Data_Self_Bill t
INNER JOIN (
	SELECT 
		OdsCustomerId,
		VPN_TRANSACTIONID,
		MAX(OdsPostingGroupAuditId) AS OdsPostingGroupAuditId
	FROM src.Esp_Ppo_Billing_Data_Self_Bill
	WHERE OdsPostingGroupAuditId <= @OdsPostingGroupAuditId
	GROUP BY OdsCustomerId,
		VPN_TRANSACTIONID) s
ON t.OdsPostingGroupAuditId = s.OdsPostingGroupAuditId
	AND t.OdsCustomerId = s.OdsCustomerId
	AND t.VPN_TRANSACTIONID = s.VPN_TRANSACTIONID
WHERE t.DmlOperation <> 'D';

GO


